### ISSUE TITLE
Implement file transmission

### ISSUE THREAD

**Issue by szyna** [mliszcz/IOSR2015#10]
Write a code which will be used to transfering a file from node to client (and vice versa) using ActiveMQ.

**Comment by mliszcz** [comment]
If you are going to work on this under [Implement-file-transmission](https://github.com/mliszcz/IOSR2015/tree/Implement-file-transmission) branch, please give that branch reasonable name according to thenaming practices:
 * http://stackoverflow.com/questions/273695/git-branch-naming-best-practices
 * https://gist.github.com/digitaljhelms/4287848

Proper name should at least contain issue number (#10)

**Comment by mliszcz** [comment]
Name of the branch ...

**Comment by szyna** [comment]
Some parts of the code implemented in this issue was used to implement issue 17 (load-balancing)
